### PR TITLE
Added FAB open direction and Item title side

### PR DESCRIPTION
**Pull request by ElegyD**
Added KCFABOpenDirection: .up and .down
Added KCFABItemTitleSide: .left and .right
Shadow Color from FAB can be changed: fab.shadowColor
Renamed .slideUp animation to .slide
Removed .slideDown animation (replaced by .slide animation with openDirection .down)
Added .slideRight animation
Some syntax corrections

### CODE REVIEW

**Comment by kciter** [comment]
Hello, @ElegyD 
Thank you for your PR. But, It confuses previous versions. 😢 
I will refer to your PR when creating version 3.0. #92

**Comment by ElegyD** [comment]
No problem! 😄

**Comment by Wndworks** [comment]
@kciter Is this setting available in the current version 3.0?

**Comment by Wndworks** [comment]
Found it: `floaty.openAnimationType = .slideDown`

**Pull request closed without merging**
